version: '3'
services:
  nuxt-app:
    build:
        context: ./
        dockerfile: ./FE/Dockerfile
    environment:
      TZ: Asia/Tokyo
      API_BASE_URL: $API_BASE_URL
    command: ['/bin/bash', '-c', 'NUXT_HOST=0.0.0.0 yarn run dev']
    working_dir: /home/nuxt-app/app/FE
    volumes:
      - ./:/home/nuxt-app/app
    ports:
      - $WEB_PORT:3000
    environment:
      - HOST=0.0.0.0
